########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description:
  This template creates an IAM role to configure the delegated administrator account -  - 'security_lake_org' solution in the repo,
  https://github.com/aws-samples/aws-security-reference-architecture-examples (sra-1ssgnse80)

Metadata:
  SRA:
    Version: 1.0
    Order: 2
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Properties
        Parameters:
          - pSRASolutionName

      - Label:
          default: Role Properties
        Parameters:
          - pSecurityLakeSubscriberRoleName
          - pSecurityLakeOrgLambdaRoleName
          - pManagementAccountId

    ParameterLabels:
      pManagementAccountId:
        default: Organization Management Account ID
      pSecurityLakeOrgLambdaRoleName:
        default: Lambda Role Name
      pSecurityLakeSubscriberRoleName:
        default: Security Lake Query Subscriber Role Name
      pSRASolutionName:
        default: SRA Solution Name

Parameters:
  pManagementAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization Management Account ID
    Type: String
  pSecurityLakeOrgLambdaRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: sra-security-lake-org-lambda
    Description: Lambda Role Name
    Type: String
  pSecurityLakeSubscriberRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: sra-security-lake-query-subscriber
    Description: SecurityLake Configuration IAM Role Name
    Type: String
  pSRASolutionName:
    AllowedValues: [sra-security-lake-org]
    Default: sra-security-lake-org
    Description: The SRA solution name. The default value is the folder name of the solution
    Type: String

Resources:
  rQuerySubscriberRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Actions require * in resource
          - id: W28
            reason: Explicit role name provided
    Properties:
      RoleName: !Ref pSecurityLakeSubscriberRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalArn:
                  - !Sub arn:${AWS::Partition}:iam::${pManagementAccountId}:role/${pSecurityLakeOrgLambdaRoleName}
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pManagementAccountId}:root
      Path: '/'
      Policies:

        - PolicyName: sra-security-lake-subscriber
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SecurityLakeSubscriber
                Effect: Allow
                Action: "*"
                Resource: '*'
        
        - PolicyName: sra-security-lake-org-policy-iam
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowReadIamActions
                Effect: Allow
                Action: iam:GetRole
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*

      Tags:
        - Key: sra-solution
          Value: !Ref pSRASolutionName
